[package]
name = "serde_newtype"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_with = "3"
serde_json = "1"
